### ISSUE TITLE
Is this meant seriously?

### ISSUE THREAD

**Issue by kangalioo** [nukeop/is-odd#4]
Or is this is a jab at https://www.npmjs.com/package/is-odd

**Comment by dtolnay** [comment]
I have been using this in production. It works great so far, no complaints. Kudos to the contributors and maintainers.

**Comment by nukeop** [comment]
> Or is this is a jab at https://www.npmjs.com/package/is-odd

Why do you denigrate my hard work?

**Comment by kangalioo** [comment]
I see[.](https://pastebin.com/raw/VhnG1dpx)

**Comment by ChocolateLoverRaj** [comment]
@kangalio the `is-odd` NPM package is a serious and useful package. So I'm guessing this one is too.
